# Generated by Django 2.2 on 2019-12-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipCode', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('landmark', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pam_number', models.IntegerField()),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipCode', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='img_url',
            field=models.CharField(max_length=208),
        ),
        migrations.AlterField(
            model_name='products',
            name='p_price',
            field=models.FloatField(),
        ),
    ]
